# name: xyz
# on:
#   workflow-dispatch:
#     input:
#       rasham:
#         required: true
#         description: "Something"
#         type: string

# jobs:
#   rasham:
#     runs-on: ubuntu-latest
#     steps:
#       - name: test
#         run: echo "Rasham"

name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        type: boolean
        required: false
        description: Run Specific Job

      custom_message:
        type: string
        required: true
        description: Printing Custom Message

jobs:
  job1:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    continue-on-error: true
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      
      - name: Printing Custom Message
        id: stp1
        run: |
             echo "${{inputs.custom_message}}"