# name: xyz
# on:
#   workflow-dispatch:
#     input:
#       rasham:
#         required: true
#         description: "Something"
#         type: string

# jobs:
#   rasham:
#     runs-on: ubuntu-latest
#     steps:
#       - name: test
#         run: echo "Rasham"
name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"


